/**
 * Native permission hygiene — Apple Guidelines 5.1.1(iii) / 2.5.1
 *
 * This is an Expo CNG project: the ios/ and android/ native directories are
 * gitignored and regenerated by `expo prebuild` at build time, so app.json is
 * the durable source of truth for permissions and display name. These tests
 * lock that config so a future prebuild cannot reintroduce the unused
 * microphone / Face ID permissions and so the photo-library purpose string
 * stays specific to the app's actual use.
 */
import { readFileSync } from "fs";
import { join } from "path";

const appJson = JSON.parse(
	readFileSync(join(__dirname, "..", "..", "app.json"), "utf8"),
) as {
	expo: {
		name: string;
		plugins: (string | [string, Record<string, unknown>])[];
	};
};

/** Find a plugin entry's options object by package name. */
function pluginConfig(name: string): Record<string, unknown> | undefined {
	const entry = appJson.expo.plugins.find(
		(p) => Array.isArray(p) && p[0] === name,
	);
	return Array.isArray(entry)
		? (entry[1] as Record<string, unknown>)
		: undefined;
}

describe("app.json — display name", () => {
	it("uses the BoothIQ brand name (not the slug)", () => {
		expect(appJson.expo.name).toBe("BoothIQ");
	});
});

describe("app.json — unused permissions are disabled at the source", () => {
	it("expo-secure-store disables the unused Face ID permission", () => {
		expect(pluginConfig("expo-secure-store")?.faceIDPermission).toBe(false);
	});

	it("expo-camera disables the unused microphone permission", () => {
		expect(pluginConfig("expo-camera")?.microphonePermission).toBe(false);
	});

	it("expo-image-picker disables camera + microphone (library-only usage)", () => {
		const picker = pluginConfig("expo-image-picker");
		expect(picker?.cameraPermission).toBe(false);
		expect(picker?.microphonePermission).toBe(false);
	});
});

describe("app.json — purpose strings are specific", () => {
	it("expo-camera scopes the camera string to QR scanning", () => {
		expect(pluginConfig("expo-camera")?.cameraPermission).toMatch(
			/scan QR codes/i,
		);
	});

	it("expo-image-picker describes the real photo-library use", () => {
		const photos = pluginConfig("expo-image-picker")?.photosPermission;
		expect(typeof photos).toBe("string");
		expect(photos as string).toMatch(/attach images to support requests/i);
		// Must not be the generic Expo default.
		expect(photos as string).not.toMatch(
			/^Allow \$\(PRODUCT_NAME\) to access your photos$/,
		);
	});
});
